name: fml
description: Flutter Markup Language
homepage: https://fml.dev
repository: https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language.git
version: 2.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  # Updated 2021/09/23
  audioplayers: ^0.20.1
  # MIT

  # Updated 2023/02/21
  camera: ^0.10.3
  # BSD-3-Clause

  # Updated 2023/02/07
  camera_windows: ^0.2.1+4
  # BSD-3-Clause

  # Updated 2023/03/19
  collection: ^1.17.0
  # BSD-3-Clause

  # Updated 2022/11/17
  # charts_flutter: ^0.12.0
  community_charts_flutter: ^1.0.1
  # Apache-2.0

  # Updated 2022/11/17
  # charts_flutter: ^0.12.0
  community_charts_common: ^1.0.1
  # Apache-2.0

  # Updated 2021/09/23
  cross_connectivity: ^3.0.5
  # BSD-3-Clause

  # Updated 2022/05/26
  cross_file: ^0.3.3+1
  # BSD-3-Clause

  # Updated 2022/05/26
  crypto: ^3.0.2
  # BSD-3-Clause
  
  # Updated 2022/05/26
  decimal: ^1.5.0
  # Apache-2.0

  # file picker with extension support
  # Updated 2022/09/01
  file_picker: ^5.0.1
  # MIT

  # Microsoft Logon
  # Updated 2023/06/06
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_core_platform_interface: ^4.8.0
  # BSD-3-Clause

  # Updated 2023/02/02
  flutter_code_editor: ^0.2.23
  # Apache-2.0, MIT

  # Updated 2021/09/23
  flutter_beacon: ^0.5.1
  # BSD-3-Clause

  # Updated 2023/03/13
  flutter_highlight: ^0.7.0
  # MIT

  # Added 2022/06/10
  flutter_html: ^3.0.0-beta.2
  # MIT

  # Updated 2022/12/29
  flutter_image_transform: ^1.0.0
  # MIT

  # Added 2023/06/06
  flutter_map: ^4.0.0
  # BSD-3-Clause

  # Updated 2023/03/19
  flutter_multi_formatter: ^2.10.2
  # MIT

  # Updated 2022/05/19
  flutter_nfc_kit: ^3.3.1
  # MIT

  # Updated 2023/06/05
  flutter_svg: ^2.0.6
  # MIT

  # Updated 2023/06/05
  flutter_typeahead: ^4.6.1
  # BSD-2-Clause

  # Updated 2022/12/30
  geolocator: ^9.0.2
  # MIT

  # Updated 2023/06/06
  google_fonts: ^4.0.4
  # Apache-2.0

  # Updated 2022/10/20
  google_mlkit_barcode_scanning: ^0.6.0
  # MIT

  # google_mlkit_face_detection: ^0.2.0

  # Updated 2022/10/20
  google_mlkit_text_recognition: ^0.6.0
  # MIT

  # Updated 2022/05/26
  google_maps_flutter: ^2.1.6
  # BSD-3-Clause

  # Updated 2022/05/26
  google_maps_flutter_web: ^0.3.3
  # BSD-3-Clause, MIT

  # Updated 2023/03/13
  highlight: ^0.7.0
  # MIT

  # Updated 2022/05/26
  hive: ^2.2.1
  # Apache-2.0

  # Updated 2023/06/06
  http: ^0.13.5
  # BSD-3-Clause

  # Updated 2022/11/06 // Our library "flutter_image_transform" is blocking this update
  image: ^3.2.2
  # MIT

  # Updated 2022/06/11
  intl: ^0.17.0
  # BSD-3-Clause

  # Updated 2022/01/29
  jaguar_jwt: ^3.0.0
  # BSD-3-Clause

  # Updated 2023/05/02
  jiffy: ^5.0.0
  # MIT

  # Updated 2023/03/13
  js: ^0.6.5
  # BSD-3-Clause

  # Updated 2023/06/06
  latlong2: ^0.8.2
  # BSD-3-Clause

  # Updated 2023/03/13
  mime: ^1.0.4
  # BSD-3-Clause

  # Updated 2023/01/05
  mqtt_client: ^9.7.4
  # BSD-3-Clause, MIT

  # Updated 2023/03/13
  ndef: ^0.3.1
  # MIT

  # Updated 2022/10/31
  open_filex: ^4.2.2
  # BSD-3-Clause, MIT

  # Updated 2022-08-30
  path: ^1.8.2
  # BSD-3-Clause

  # Updated 2022/06/08
  path_provider: ^2.0.11
  # BSD-3-Clause

  # Updated 2022/10/21
  perfect_freehand: ^1.0.4
  # MIT

  # Updated 2022/05/26 - Warning, updating petitparser could potentially break the EVAL().
  petitparser: ^5.0.0
  # MIT

  # Updated 2022/05/26
  photo_view: ^0.14.0
  # MIT

  # Updated 2022/05/26
  pointycastle: ^3.7.3
  # MIT

  # Updated 2022/05/26
  provider: ^6.0.3
  # MIT

  # Updated 2023/03/13
  quiver: ^3.2.1
  # Apache-2.0

  # Updated 2022/05/26
  # syncfusion_flutter_charts: ^20.1.57
  # https://pub.dev/packages/syncfusion_flutter_charts/license

  # Updated 2023/03/13
  stream_channel: ^2.1.1
  # BSD-3-Clause

  # Updated 2022/05/26
  web_socket_channel: ^2.2.0
  # BSD-3-Clause

  # Updated 2023/05/25
  universal_html: ^2.2.2
  # Apache-2.0

  # Updated 2022/09/28
  url_launcher: ^6.1.5
  # BSD-3-Clause

  # Updated 2022/05/19
  uuid: ^3.0.6
  # MIT

  # Updated 2021/09/23
  validators: ^3.0.0
  # MIT

  # Updated 2022/12/14
  video_player: ^2.4.9
  # BSD-3-Clause

  # Updated 2023/4/3
  video_player_win: ^2.2.2
  # BSD-3-Clause

  # Updated 2023/02/28
  visibility_detector: ^0.3.3
  # BSD-3-Clause

  # Updated 2023/03/19
  webview_flutter: ^4.0.6
  # BSD-3-Clause

  # Updated 2022/05/26
  xml: ^6.1.0
  # MIT

  # Updated 2023/02/06
  xml2json: ^5.3.6
  # MIT

  # Updated 2021/09/23
  zxing_lib: ^0.6.0
  # Apache 2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.21.1
  dependency_validator: ^3.2.2
  lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/fonts/
    - assets/images/

    # the applications folder is used for
    # local (standalone) apps.
    - assets/applications/
    - assets/applications/sample/
    - assets/applications/sample/images/
    - assets/applications/sample/templates/

    # fmlpad
    - assets/applications/
    - assets/applications/fmlpad/

  fonts:
    - family: icons
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
