name: fml
description: Flutter Markup Language

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  yaml: ^3.1.0
  # MIT

  flutter:
    sdk: flutter

  # Updated 2021/09/23
  audioplayers: 0.20.1
  # MIT

  # Updated 2022/10/20
  camera: 0.10.0+3
  # BSD-3-Clause

  # Updated 2022/11/17
  # charts_flutter: ^0.12.0
  community_charts_flutter: ^1.0.0
  # Apache-2.0

  # Updated 2021/09/23
  cross_connectivity: 3.0.5
  # BSD-3-Clause

  # Updated 2022/05/26
  cross_file: 0.3.3+1
  # BSD-3-Clause

  # Updated 2022/05/26
  crypto: 3.0.2
  # BSD-3-Clause

  # Updated 2021/09/23
  datetime_picker_formfield: 2.0.0
  # MIT

  # Updated 2022/05/31
  date_time_picker: ^2.1.0
  # UNKNOWN
  
  # Updated 2022/05/26
  decimal: 1.5.0
  # Apache-2.0
  
  # file picker with extension support
  # Updated 2022/09/01
  file_picker: 5.0.1
  # MIT

  # Microsoft Logon
  # Updated 2022/09/20
  firebase_auth: 3.9.0
  firebase_core: 1.22.0
  # BSD-3-Clause

  # Updated 2021/09/23
  # flutter_blue: 0.8.0
  # BSD-3-Clause

  # Added 2022/06/10
  flutter_html: ^3.0.0-alpha.5
  # MIT

  # Updated 2022/12/29
  flutter_image_transform: ^1.0.0
  # MIT

  # Added 2022/12/13
  flutter_map: 3.0.0
  # BSD-3-Clause

  # Added 2022/12/13
  flutter_map_marker_cluster: 1.0.1
  # BSD-3-Clause

  # Updated 2022/05/26
  flutter_multi_formatter: 2.5.7
  # MIT

  # Updated 2022/05/19
  flutter_nfc_kit: ^3.3.1
  # MIT

  # Updated 2022/08/09
  flutter_svg: 1.1.4
  # MIT

  # Updated 2022/05/19
  flutter_typeahead: 4.0.0
  # BSD-2-Clause

  # Updated 2022/05/26
  google_fonts: 3.0.1
  # Apache-2.0

  # Updated 2022/10/20
  google_mlkit_barcode_scanning: 0.4.0
  # MIT

  # google_mlkit_face_detection: 0.2.0

  # Updated 2022/10/20
  google_mlkit_text_recognition: 0.4.0
  # MIT

  # Updated 2022/05/26
  google_maps_flutter: 2.1.6
  # BSD-3-Clause

  # Updated 2022/05/26
  google_maps_flutter_web: 0.3.3
  # BSD-3-Clause, MIT

  # Updated 2022/05/26
  hive: 2.2.1
  # Apache-2.0

  # Updated 2022/08/22
  http: 0.13.5
  # BSD-3-Clause

  # Updated 2022/11/06
  image: 3.2.2
  # MIT

  # Updated 2022/01/29
  jaguar_jwt: 3.0.0
  # BSD-3-Clause

  # Updated 2022/12/13
  latlong2: 0.8.1
  # BSD-3-Clause

  # Updated 2022/12/29
  location: 5.0.0-dev.8
  # MIT

  # Updated 2022/05/26
  mime: 1.0.2
  # BSD-3-Clause

  # Updated 2022/05/26
  mqtt_client: 9.6.8
  # BSD-3-Clause, MIT

  # Updated 2022/10/31
  open_filex: 4.2.2
  # BSD-3-Clause, MIT

  # Updated 2022-08-30
  path: 1.8.2
  # BSD-3-Clause

  # Updated 2022/06/08
  path_provider: 2.0.11
  # BSD-3-Clause

  # Updated 2022/10/21
  perfect_freehand: ^1.0.4
  # MIT

  # Updated 2022/05/26 - Warning, updating petitparser could potentially break the EVAL().
  petitparser: 5.0.0
  # MIT

  # Updated 2022/05/26
  photo_view: 0.14.0
  # MIT

  # Updated 2022/03/30
  platform: ^3.1.0
  # BSD-3-Clause

  # Updated 2022/05/26
  pointycastle: 3.6.0
  # MIT

  # Updated 2022/05/26
  provider: 6.0.3
  # MIT

  # Updated 2022/05/26
  # syncfusion_flutter_charts: 20.1.57
  # https://pub.dev/packages/syncfusion_flutter_charts/license

  # Updated 2022/12/28
  stream_channel:
  # BSD-3-Clause

  # Updated 2022/05/26
  web_socket_channel: 2.2.0
  # BSD-3-Clause

  # Updated 2022/09/28
  url_launcher: 6.1.5
  # BSD-3-Clause

  # Updated 2022/05/19
  uuid: 3.0.6
  # MIT

  # Updated 2021/09/23
  validators: 3.0.0
  # MIT

  # Updated 2022/12/14
  video_player: 2.4.9
  # BSD-3-Clause

  # Updated 2022/05/26
  webview_flutter: 4.0.0
  # BSD-3-Clause

  # Updated 2022/05/26
  xml: 6.1.0
  # MIT

  # Updated 2022/06/17
  xml2json: 5.3.3
  # MIT

  # Updated 2021/09/23
  zxing_lib: 0.6.0
  # Apache 2.0

  # Updated 2022/06/11
  intl: ^0.17.0
  # BSD-3-Clause
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.21.1

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/fonts/
    - assets/templates/
    - assets/images/

  fonts:
    - family: icons
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
