name: fml_example
description: Flutter Markup Language
homepage: https://fml.dev
repository: https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language.git
version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fml:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/applications/

    # counter app
    - assets/applications/example/
    - assets/applications/example/images/
    - assets/applications/example/templates/

    # fmlpad app
    - assets/applications/fmlpad/
    - assets/applications/fmlpad/images/
    - assets/applications/fmlpad/templates/